---

- name: Create Share Folder
  file:
    path: ~/pentest-tools
    mode: 0755
    state: directory

- name: Copy all Share Tools over
  copy:
    src: share/
    dest: ~/pentest-tools/

- name: Install some pentest tools
  become: true
  apt:
    pkg:
    - seclists
    - dirsearch
    - stegseek
    - steghide
    state: present