---

- name: Create Share Folder
  file:
    path: ~/pentest-tools
    mode: 0755
    state: directory

- name: Copy all Share Tools over
  copy:
    src: share/
    dest: ~/pentest-tools/

- name: Install some pentest tools
  become: true
  apt:
    pkg:
    - seclists
    - dirsearch
    - stegseek
    - steghide
    - nishang
    state: present

- name: install nuclei
  shell: go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest

- name: install rassetfinder by Richard
  script: install-rassetfinder.sh

- name: Check if OneRulePasswords exists
  stat:
    path: ~/OneRuleToRuleThemAll.rule
  register: OneRulePasswords

- name: download OneRulePasswords
  shell: wget https://raw.githubusercontent.com/NotSoSecure/password_cracking_rules/master/OneRuleToRuleThemAll.rule -P ~/
  when: not OneRulePasswords.stat.exists

- name: install breach-parse
  script: install-breach-parse.sh