---
- include_tasks: user_group.yml

- name: Add Docker Repo to Apt
  become: True
  script: add-docker-apt.sh

- name: Install docker
  become: true
  apt:
    pkg:
    - docker.io
    - docker-compose-plugin

- name: Enable Docker Service
  become: True
  service:
    enabled: True
    name: docker
    state: started

- name: Make sure docker directory exists for our services
  file:
    path: ~/docker
    mode: 0755
    state: directory


- include_tasks: portainer.yml