---

- name: Create portainer folder
  file:
    path: ~/docker/portainer
    mode: 755
    state: directory

- name: Copy portainer config over
  copy:
    src: portainer.yml
    dest: ~/docker/portainer/portainer.yml

- name: Start portainer in background
  shell: docker compose up -d -f ~/docker/portainer/portainer.yml
