- name: Ensure Docker Group Exists
  become: True
  group:
    name: docker
    state: present

- name: Add user to the docker role
  become: True
  user:
    name: "{{ user.name }}"
    groups: docker
    append: yes