---

- name: Update & Upgrade
  become: True
  apt:
    update_cache: true
    upgrade: false

- name: Install python3-venv
  become: True
  apt:
    name: python3-venv
    state: present

- name: Install pipx
  ansible.builtin.pip:
    name: pipx

- include_tasks: pipx.yml
- include_tasks: personal.yml