---

- name: Update & Upgrade
  become: True
  apt:
    update_cache: true
    upgrade: false

- name: Install pipx
  ansible.builtin.pip:
    name: pipx

- include_tasks: pipx.yml
- include_tasks: personal.yml