- name: Check if Oh My Zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_folder


- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_folder.stat.exists

- name: Create Local Share Fonts Folder
  file:
    path: ~/.local/share/fonts
    mode: 0755
    state: directory

- name: Copy MeloLGS Fonts over
  copy:
    src: fonts/*.ttf
    dest: ~/.local/share/fonts/

- name: Install a color versions
  apt:
    pkg:
    - exa

- name: Install a Chrome via online .deb
  apt:
    deb: https://www.google.com/chrome/next-steps.html?brand=YTUH&platform=linux&statcb=0&installdataindex=empty&defaultbrowser=0#