- name: Check if Oh My Zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_folder


- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_folder.stat.exists

- name: Create Local Share Fonts Folder
  file:
    path: ~/.local/share/fonts
    mode: 0755
    state: directory

- name: Copy MeloLGS Bold Italic
  copy:
    src: "fonts/MesloLGS NF Bold Italic.ttf"
    dest: "~/.local/share/fonts/MesloLGS NF Bold Italic.ttf"

- name: Copy MeloLGS Italic
  copy:
    src: "fonts/MesloLGS NF Italic.ttf"
    dest: "~/.local/share/fonts/MesloLGS NF Italic.ttf"

- name: Copy MeloLGS Bold
  copy:
    src: "fonts/MesloLGS NF Bold.ttf"
    dest: "~/.local/share/fonts/MesloLGS NF Bold.ttf"

- name: Copy MeloLGS Regular
  copy:
    src: "fonts/MesloLGS NF Regular.ttf"
    dest: "~/.local/share/fonts/MesloLGS NF Regular.ttf"


- name: Install a color versions
  become: true
  apt:
    pkg:
    - exa

- name: Install a Chrome via online .deb
  become: true
  apt:
    deb: https://www.google.com/chrome/next-steps.html?brand=YTUH&platform=linux&statcb=0&installdataindex=empty&defaultbrowser=0#