- name: Check if Oh My Zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_folder

- name: Check if powerlevel10k exists
  stat:
    path: ~/.oh-my-zsh/custom/themes/powerlevel10k
  register: powerlevel10k_folder

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_folder.stat.exists

- name: Create Local Share Fonts Folder
  file:
    path: ~/.local/share/fonts
    mode: 0755
    state: directory

- name: Copy MeloLGS Fonts
  copy:
    src: fonts/
    dest: ~/.local/share/fonts/

- name: Install Powerlevel10k
  shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  when: not powerlevel10k_folder.stat.exists

- name: Copy .zshrc
  copy:
    src: ".zshrc"
    dest: "~/.zshrc"

- name : Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest:  ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Copy .p10k.zsh
  copy:
    src: ".p10k.zsh"
    dest: "~/.p10k.zsh"

- name: Install some apps
  become: true
  apt:
    pkg:
    - exa
    - bat
    - code
    - dbeaver
    - golang
    - flameshot
    - libssl-dev
    - libbz2-dev
    - libsqlite3-dev
    - python3-tk
    - liblzma-dev
    - tk-dev
    - libreadline-dev
    state: present

- name: Install a Chrome via online .deb
  become: true
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    state: present

- name: Install Obsidian via .deb
  become: true
  apt:
    deb: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.3.7/obsidian_1.3.7_amd64.deb
    state: present

- name: Change Desktop Background
  script: change-bg.sh

- name: Copy Bookmarks File over
  copy:
    src: browser/bookmarks_22_05_2023.html
    dest: ~/bookmarks_22_05_2023.html

- name: Copy XFCE Panel Settings
  copy:
    src: xfce-panel.tar.bz2
    dest: ~/xfce-panel.tar.bz2

- name: Import XFCE Panel Configuration
  script: import-xfce-panel.sh